name: WINDOWS BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: files

    - name: Package Application
      uses: andrewstech/youtube-dl-server-winbuilder@main
      with:
        path: files
        
    - uses: papeloto/action-zip@v1
      with:
        files: dist/windows/
        dest: video.zip
          
    - uses: actions/upload-artifact@v2
      with:
        name: alpha
        path: video.zip
  
